//API Endpoints

//Security Endpoints
### register a user
POST http://{{url}}/auth/register

{
    "username": "user1",
    "password": "pass12345"
}


### login
POST http://{{url}}/auth/login

{
    "username": "ADMIN",
    "password": "1234"
}

### test user token
GET http://{{url}}/protected/user_demo
AUTHORIZATION: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjEzODMyNTQsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.R1Zdn-KkMQd8RAgn7kfLPRxpS5uzoOUvUyhRR94sPUM

### test admin token
GET http://{{url}}/protected/admin_demo
AUTHORIZATION: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjEzODMxNDIsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.1kn_gzVa_pyMfGZBpcSJeZ5kGLYvJr4GogsKPmULCyY



//Basket & Product Endpoints
### post a product to specific basket -- User Token
POST https://{{url}}/baskets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjE0MTgzNTksInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.rd6I26IuCmjMhPxqfGju8OS4vOdJd4fKrfCwclMlHNQ

{
  "basketId": "2",
  "productId": "3",
  "amount": "10"
}


### create a product -- Admin Token
POST https://{{url}}/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjE0MTg0MjEsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.y6VJ8BuQ5OhxpAdrsRLc4yD1ROn4Q2UfGKQSQzFxXg8

{
  "name": "Apple",
  "price": "4.5",
  "category": "FOOD"
}

### find a specific product -- Admin Token
GET https://{{url}}/products/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjE0MTg0MjEsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.y6VJ8BuQ5OhxpAdrsRLc4yD1ROn4Q2UfGKQSQzFxXg8

### find all existing products -- Admin Token
GET https://{{url}}/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjE0MTg0MjEsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.y6VJ8BuQ5OhxpAdrsRLc4yD1ROn4Q2UfGKQSQzFxXg8

### update a product -- Admin Token
PUT https://{{url}}/products/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjE0MTg0MjEsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.y6VJ8BuQ5OhxpAdrsRLc4yD1ROn4Q2UfGKQSQzFxXg8

{
  "name": "Phone",
  "price": "50.2",
  "category": "ELECTRONICS"
}

### delete product -- Admin Token
DELETE https://{{url}}/products/1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoiQURNSU4iLCJleHAiOjE3NjE0MTg0MjEsInJvbGVzIjoiQWRtaW4iLCJ1c2VybmFtZSI6IkFETUlOIn0.y6VJ8BuQ5OhxpAdrsRLc4yD1ROn4Q2UfGKQSQzFxXg8

### find all products from specific basket -- User Token
GET https://{{url}}/basketproducts/2
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJcIk1hZ251cyBTaW1vbnNlblwiIiwic3ViIjoidXNlcjEiLCJleHAiOjE3NjE0MTgzNTksInJvbGVzIjoiVXNlciIsInVzZXJuYW1lIjoidXNlcjEifQ.rd6I26IuCmjMhPxqfGju8OS4vOdJd4fKrfCwclMlHNQ

### buy function, with basket id.
POST http://{{url}}/baskets/buy/2


### Get Receipt
GET https://{{url}}/receipt/2